/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * api.trace.moe
 * api.trace.moe
 * OpenAPI spec version: 1.0.1
 */

export interface AnilistTitle {
  /**
   * English title
   * @nullable
   */
  english: string | null;
  /**
   * Native title
   * @nullable
   */
  native: string | null;
  /** Romaji title */
  romaji: string;
}
