/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * api.trace.moe
 * api.trace.moe
 * OpenAPI spec version: 1.0.1
 */
import type { AnilistTitle } from './anilistTitle';

export interface Anilist {
  /** Anilist ID */
  id: number;
  /**
   * MyAnimeList ID
   * @nullable
   */
  idMal: number | null;
  /** Adult anime or not */
  isAdult: boolean;
  /** Alias titles */
  synonyms: string[];
  title: AnilistTitle;
}
