/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * api.trace.moe
 * api.trace.moe
 * OpenAPI spec version: 1.0.1
 */
import type { Error } from './error';

/**
 * Image is malformed, or some params are incorrect
 */
export type ErrorBadRequestResponse = Error;
