/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * api.trace.moe
 * api.trace.moe
 * OpenAPI spec version: 1.0.1
 */

export type GetSearchParams = {
/**
 * Include Anilist info
 */
anilistInfo?: string;
/**
 * Cut black borders
 */
cutBorders?: string;
/**
 * Image URL
 */
url: string;
/**
 * Filter by Anilist ID
 */
anilistID?: number;
};
