/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * api.trace.moe
 * api.trace.moe
 * OpenAPI spec version: 1.0.1
 */
import type { ResultEpisodeOneOfItem } from './resultEpisodeOneOfItem';

/**
 * The extracted episode number from filename
 */
export type ResultEpisode = number | null | string | null | ResultEpisodeOneOfItem[];
