/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * api.trace.moe
 * api.trace.moe
 * OpenAPI spec version: 1.0.1
 */
import type { Anilist } from './anilist';

/**
 * The matching Anilist ID or Anilist info
 */
export type ResultAnilist = number | Anilist;
