/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * api.trace.moe
 * api.trace.moe
 * OpenAPI spec version: 1.0.1
 */
import type { Result } from './result';

export interface SearchResult {
  /** Error message */
  error: string;
  /** frames compared for image search */
  frameCount: number;
  /** Search results */
  result: Result[];
}
