/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * api.trace.moe
 * api.trace.moe
 * OpenAPI spec version: 1.0.1
 */

export interface User {
  /** Number of parallel search requests you can make */
  concurrency: number;
  /** IP address (guest) or email address (user) */
  id: string;
  /** Your priority in search queue */
  priority: number;
  /** Search quota you have for this month */
  quota: number;
  /** Search quota you have used this month */
  quotaUsed: number;
}
