/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Jikan API
 * [Jikan](https://jikan.moe) is an **Unofficial** MyAnimeList API.
It scrapes the website to satisfy the need for a complete API - which MyAnimeList lacks.

# Information

⚡ Jikan is powered by its awesome backers - 🙏 [Become a backer](https://www.patreon.com/jikan)

## Rate Limiting

| Duration | Requests |
|----|----|
| Daily | **Unlimited** |
| Per Minute | 60 requests |
| Per Second | 3 requests |

Note: It's still possible to get rate limited from MyAnimeList.net instead.


## JSON Notes
- Any property (except arrays or objects) whose value does not exist or is undetermined, will be `null`.
- Any array or object property whose value does not exist or is undetermined, will be empty.
- Any `score` property whose value does not exist or is undetermined, will be `0`.
- All dates and timestamps are returned in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format and in UTC timezone

## Caching
By **CACHING**, we refer to the data parsed from MyAnimeList which is stored temporarily on our servers to provide better API performance.

All requests are cached for **24 hours**.

The following response headers will detail cache information.

| Header | Remarks |
| ---- | ---- |
| `Expires` | Cache expiry date |
| `Last-Modified` | Cache set date |
| `X-Request-Fingerprint` | Unique request fingerprint (only for cachable requests, not queries) |


Note: `X-Request-Fingerprint` will only be available on single resource requests and their child endpoints. e.g `/anime/1`, `/anime/1/relations`.
They won't be available on pages which perform queries, like /anime, or /top/anime, etc.

## Allowed HTTP(s) requests

**Jikan REST API does not provide authenticated requests for MyAnimeList.** This means you can not use it to update your anime/manga list.
Only GET requests are supported which return READ-ONLY data.

## HTTP Responses

All error responses are accompanied by a JSON Error response.

| Exception | HTTP Status | Remarks |
| ---- | ---- | ---- |
| N/A | `200 - OK` | The request was successful |
| N/A | `304 - Not Modified` | You have the latest data (Cache Validation response) |
| `BadRequestException`,`ValidationException` | `400 - Bad Request` | You've made an invalid request. Recheck documentation |
| `BadResponseException` | `404 - Not Found` | The resource was not found or MyAnimeList responded with a `404` |
| `BadRequestException` | `405 - Method Not Allowed` | Requested Method is not supported for resource. Only `GET` requests are allowed |
| `RateLimitException` | `429 - Too Many Request` | You are being rate limited by Jikan or MyAnimeList is rate-limiting our servers (specified in the error response) |
| `UpstreamException`,`ParserException`,etc. | `500 - Internal Server Error` | Something didn't work. Try again later. If you see an error response with a `report_url` URL, please click on it to open an auto-generated GitHub issue |
| `ServiceUnavailableException` | `503 - Service Unavailable` | In most cases this is intentionally done if the service is down for maintenance. |

## JSON Error Response

```json
 {
     "status": 500,
     "type": "InternalException",
     "message": "Exception Message",
     "error": "Exception Trace",
     "report_url": "https://github.com..."
  }
```

| Property | Remarks |
| ---- | ---- |
| `status` | Returned HTTP Status Code |
| `type` | Thrown Exception |
| `message` | Human-readable error message |
| `error` | Error response and trace from the API |
| `report_url` | Clicking this would redirect you to a generated GitHub issue |


## Cache Validation

- All requests return a `ETag` header which is an MD5 hash of the response
- You can use this hash to verify if there's new or updated content by suppliying it as the value for the `If-None-Match` in your next request header
- You will get a HTTP `304 - Not Modified` response if the content has not changed
- If the content has changed, you'll get a HTTP `200 - OK` response with the updated JSON response

![Cache Validation](https://i.imgur.com/925ozVn.png 'Cache Validation')

## Disclaimer

- Jikan is not affiliated with MyAnimeList.net.
- Jikan is a free, open-source API. Please use it responsibly.

----

By using the API, you are agreeing to Jikan's [terms of use](https://jikan.moe/terms) policy.

[v3 Documentation](https://jikan.docs.apiary.io/) - [Wrappers/SDKs](https://github.com/jikan-me/jikan#wrappers) - [Report an issue](https://github.com/jikan-me/jikan-rest/issues/new) - [Host your own server](https://github.com/jikan-me/jikan-rest)
 * OpenAPI spec version: 4.0.0
 */

export * from './anime';
export * from './animeCharacters';
export * from './animeCharactersDataItem';
export * from './animeCharactersDataItemCharacter';
export * from './animeCharactersDataItemVoiceActorsItem';
export * from './animeCharactersDataItemVoiceActorsItemPerson';
export * from './animeEpisode';
export * from './animeEpisodes';
export * from './animeEpisodesAllOf';
export * from './animeEpisodesAllOfDataItem';
export * from './animeFull';
export * from './animeFullExternalItem';
export * from './animeFullRating';
export * from './animeFullRelationsItem';
export * from './animeFullSeason';
export * from './animeFullStatus';
export * from './animeFullStreamingItem';
export * from './animeFullTheme';
export * from './animeFullType';
export * from './animeImages';
export * from './animeImagesJpg';
export * from './animeImagesWebp';
export * from './animeMeta';
export * from './animeNews';
export * from './animeRating';
export * from './animeRelations';
export * from './animeRelationsDataItem';
export * from './animeReview';
export * from './animeReviewReactions';
export * from './animeReviews';
export * from './animeReviewsAllOf';
export * from './animeReviewsAllOfDataItem';
export * from './animeReviewsAllOfDataItemAllOf';
export * from './animeSearch';
export * from './animeSearchAllOf';
export * from './animeSearchQueryOrderby';
export * from './animeSearchQueryRating';
export * from './animeSearchQueryStatus';
export * from './animeSearchQueryType';
export * from './animeSeason';
export * from './animeStaff';
export * from './animeStaffDataItem';
export * from './animeStaffDataItemPerson';
export * from './animeStatistics';
export * from './animeStatisticsData';
export * from './animeStatisticsDataScoresItem';
export * from './animeStatus';
export * from './animeThemes';
export * from './animeThemesData';
export * from './animeType';
export * from './animeUserupdates';
export * from './animeUserupdatesAllOf';
export * from './animeUserupdatesAllOfDataItem';
export * from './animeVideos';
export * from './animeVideosData';
export * from './animeVideosDataEpisodesItem';
export * from './animeVideosDataMusicVideosItem';
export * from './animeVideosDataMusicVideosItemMeta';
export * from './animeVideosDataPromoItem';
export * from './animeVideosEpisodes';
export * from './animeVideosEpisodesAllOf';
export * from './animeVideosEpisodesAllOfDataItem';
export * from './broadcast';
export * from './character';
export * from './characterAnime';
export * from './characterAnimeDataItem';
export * from './characterFull';
export * from './characterFullAnimeItem';
export * from './characterFullMangaItem';
export * from './characterFullVoicesItem';
export * from './characterImages';
export * from './characterImagesJpg';
export * from './characterImagesWebp';
export * from './characterManga';
export * from './characterMangaDataItem';
export * from './characterMeta';
export * from './characterPictures';
export * from './characterPicturesDataItem';
export * from './characterVoiceActors';
export * from './characterVoiceActorsDataItem';
export * from './charactersSearch';
export * from './charactersSearchAllOf';
export * from './charactersSearchQueryOrderby';
export * from './club';
export * from './clubAccess';
export * from './clubCategory';
export * from './clubMember';
export * from './clubMemberDataItem';
export * from './clubRelations';
export * from './clubRelationsData';
export * from './clubSearchQueryCategory';
export * from './clubSearchQueryOrderby';
export * from './clubSearchQueryType';
export * from './clubStaff';
export * from './clubStaffDataItem';
export * from './clubsSearch';
export * from './clubsSearchAllOf';
export * from './commonImages';
export * from './commonImagesJpg';
export * from './continuingParameter';
export * from './daterange';
export * from './daterangeProp';
export * from './daterangePropFrom';
export * from './daterangePropTo';
export * from './entryMeta';
export * from './entryRecommendations';
export * from './entryRecommendationsDataItem';
export * from './entryRecommendationsDataItemEntry';
export * from './externalLinks';
export * from './externalLinksDataItem';
export * from './forum';
export * from './forumDataItem';
export * from './forumDataItemLastComment';
export * from './genre';
export * from './genreQueryFilter';
export * from './genres';
export * from './getAnimeById200';
export * from './getAnimeEpisodeById200';
export * from './getAnimeEpisodesParams';
export * from './getAnimeForumFilter';
export * from './getAnimeForumParams';
export * from './getAnimeFullById200';
export * from './getAnimeGenresParams';
export * from './getAnimeNewsParams';
export * from './getAnimeRelations200';
export * from './getAnimeReviewsParams';
export * from './getAnimeSearchParams';
export * from './getAnimeUserUpdatesParams';
export * from './getAnimeVideosEpisodesParams';
export * from './getCharacterById200';
export * from './getCharacterFullById200';
export * from './getCharactersSearchParams';
export * from './getClubMembers200';
export * from './getClubMembersParams';
export * from './getClubsById200';
export * from './getClubsSearchParams';
export * from './getMagazinesParams';
export * from './getMangaById200';
export * from './getMangaFullById200';
export * from './getMangaGenresParams';
export * from './getMangaNewsParams';
export * from './getMangaRelations200';
export * from './getMangaReviewsParams';
export * from './getMangaSearchParams';
export * from './getMangaTopicsFilter';
export * from './getMangaTopicsParams';
export * from './getMangaUserUpdatesParams';
export * from './getPeopleSearchParams';
export * from './getPersonById200';
export * from './getPersonFullById200';
export * from './getProducerById200';
export * from './getProducerFullById200';
export * from './getProducersParams';
export * from './getRandomAnime200';
export * from './getRandomCharacters200';
export * from './getRandomManga200';
export * from './getRandomPeople200';
export * from './getRandomUsers200';
export * from './getRecentAnimeRecommendationsParams';
export * from './getRecentAnimeReviewsParams';
export * from './getRecentMangaRecommendationsParams';
export * from './getRecentMangaReviewsParams';
export * from './getSchedulesFilter';
export * from './getSchedulesKids';
export * from './getSchedulesParams';
export * from './getSchedulesSfw';
export * from './getSeasonFilter';
export * from './getSeasonNowFilter';
export * from './getSeasonNowParams';
export * from './getSeasonParams';
export * from './getSeasonUpcomingFilter';
export * from './getSeasonUpcomingParams';
export * from './getTopAnimeParams';
export * from './getTopCharactersParams';
export * from './getTopMangaParams';
export * from './getTopPeopleParams';
export * from './getTopReviews200';
export * from './getTopReviews200Data';
export * from './getTopReviews200DataAllOf';
export * from './getTopReviews200DataAllOfDataItem';
export * from './getTopReviews200DataAllOfDataItemAnyOf';
export * from './getTopReviews200DataAllOfDataItemAnyOfAllOf';
export * from './getTopReviews200DataAllOfDataItemAnyOfAllOfTwo';
export * from './getTopReviews200DataAllOfDataItemAnyOfFour';
export * from './getTopReviews200DataAllOfDataItemAnyOfFourAllOf';
export * from './getTopReviews200DataAllOfDataItemAnyOfFourAllOfTwo';
export * from './getTopReviewsParams';
export * from './getUserAnimelistParams';
export * from './getUserById200';
export * from './getUserClubsParams';
export * from './getUserFavorites200';
export * from './getUserFriendsParams';
export * from './getUserFullProfile200';
export * from './getUserHistoryParams';
export * from './getUserHistoryType';
export * from './getUserMangaListParams';
export * from './getUserProfile200';
export * from './getUserRecommendationsParams';
export * from './getUserReviews200';
export * from './getUserReviews200Data';
export * from './getUserReviews200DataAllOf';
export * from './getUserReviews200DataAllOfDataItem';
export * from './getUserReviews200DataAllOfDataItemAnyOf';
export * from './getUserReviews200DataAllOfDataItemAnyOfAllOf';
export * from './getUserReviews200DataAllOfDataItemAnyOfAllOfTwo';
export * from './getUserReviews200DataAllOfDataItemAnyOfFour';
export * from './getUserReviews200DataAllOfDataItemAnyOfFourAllOf';
export * from './getUserReviews200DataAllOfDataItemAnyOfFourAllOfTwo';
export * from './getUserReviewsParams';
export * from './getUsersSearchParams';
export * from './getWatchRecentPromosParams';
export * from './history';
export * from './kidsParameter';
export * from './limitParameter';
export * from './magazine';
export * from './magazines';
export * from './magazinesAllOf';
export * from './magazinesQueryOrderby';
export * from './malUrl';
export * from './malUrl2';
export * from './manga';
export * from './mangaCharacters';
export * from './mangaCharactersDataItem';
export * from './mangaFull';
export * from './mangaFullExternalItem';
export * from './mangaFullRelationsItem';
export * from './mangaFullStatus';
export * from './mangaFullType';
export * from './mangaImages';
export * from './mangaImagesJpg';
export * from './mangaImagesWebp';
export * from './mangaMeta';
export * from './mangaNews';
export * from './mangaPictures';
export * from './mangaReview';
export * from './mangaReviewReactions';
export * from './mangaReviews';
export * from './mangaReviewsAllOf';
export * from './mangaReviewsAllOfDataItem';
export * from './mangaReviewsAllOfDataItemAllOf';
export * from './mangaSearch';
export * from './mangaSearchAllOf';
export * from './mangaSearchQueryOrderby';
export * from './mangaSearchQueryStatus';
export * from './mangaSearchQueryType';
export * from './mangaStatistics';
export * from './mangaStatisticsData';
export * from './mangaStatisticsDataScoresItem';
export * from './mangaStatus';
export * from './mangaType';
export * from './mangaUserupdates';
export * from './mangaUserupdatesAllOf';
export * from './mangaUserupdatesAllOfDataItem';
export * from './moreinfo';
export * from './moreinfoData';
export * from './n400Response';
export * from './news';
export * from './newsDataItem';
export * from './pageParameter';
export * from './pagination';
export * from './paginationPagination';
export * from './paginationPlus';
export * from './paginationPlusPagination';
export * from './paginationPlusPaginationItems';
export * from './peopleImages';
export * from './peopleImagesJpg';
export * from './peopleSearch';
export * from './peopleSearchAllOf';
export * from './peopleSearchQueryOrderby';
export * from './person';
export * from './personAnime';
export * from './personAnimeDataItem';
export * from './personFull';
export * from './personFullAnimeItem';
export * from './personFullMangaItem';
export * from './personFullVoicesItem';
export * from './personManga';
export * from './personMangaDataItem';
export * from './personMeta';
export * from './personPictures';
export * from './personVoiceActingRoles';
export * from './personVoiceActingRolesDataItem';
export * from './pictures';
export * from './picturesDataItem';
export * from './picturesVariants';
export * from './picturesVariantsDataItem';
export * from './preliminaryParameter';
export * from './producer';
export * from './producerFull';
export * from './producerFullExternalItem';
export * from './producers';
export * from './producersAllOf';
export * from './producersQueryOrderby';
export * from './random';
export * from './randomDataItem';
export * from './recommendations';
export * from './recommendationsAllOf';
export * from './recommendationsAllOfDataItem';
export * from './recommendationsAllOfDataItemEntryItem';
export * from './relation';
export * from './reviewsCollection';
export * from './reviewsCollectionDataItem';
export * from './schedules';
export * from './schedulesAllOf';
export * from './searchQuerySort';
export * from './seasons';
export * from './seasonsDataItem';
export * from './sfwParameter';
export * from './spoilerParameter';
export * from './spoilersParameter';
export * from './streamingLinks';
export * from './streamingLinksDataItem';
export * from './title';
export * from './topAnimeFilter';
export * from './topMangaFilter';
export * from './topReviewsTypeEnum';
export * from './trailer';
export * from './trailerBase';
export * from './trailerImages';
export * from './trailerImagesImages';
export * from './unapprovedParameter';
export * from './userAbout';
export * from './userAboutDataItem';
export * from './userAnimeListStatusFilter';
export * from './userById';
export * from './userClubs';
export * from './userClubsAllOf';
export * from './userClubsAllOfDataItem';
export * from './userFavorites';
export * from './userFavoritesAnimeItem';
export * from './userFavoritesAnimeItemAllOf';
export * from './userFavoritesCharactersItem';
export * from './userFavoritesMangaItem';
export * from './userFavoritesMangaItemAllOf';
export * from './userFriends';
export * from './userFriendsAllOf';
export * from './userFriendsAllOfDataItem';
export * from './userFriendsAllOfDataItemAllOf';
export * from './userFriendsAllOfDataItemAllOfTwo';
export * from './userHistory';
export * from './userImages';
export * from './userImagesJpg';
export * from './userImagesWebp';
export * from './userMangaListStatusFilter';
export * from './userMeta';
export * from './userProfile';
export * from './userProfileFull';
export * from './userProfileFullExternalItem';
export * from './userProfileFullStatistics';
export * from './userProfileFullStatisticsAnime';
export * from './userProfileFullStatisticsManga';
export * from './userStatistics';
export * from './userStatisticsData';
export * from './userStatisticsDataAnime';
export * from './userStatisticsDataManga';
export * from './userUpdates';
export * from './userUpdatesData';
export * from './userUpdatesDataAnimeItem';
export * from './userUpdatesDataAnimeItemAllOf';
export * from './userUpdatesDataAnimeItemAllOfTwo';
export * from './userUpdatesDataMangaItem';
export * from './userUpdatesDataMangaItemAllOf';
export * from './userUpdatesDataMangaItemAllOfTwo';
export * from './usersSearch';
export * from './usersSearchAllOf';
export * from './usersSearchAllOfDataItem';
export * from './usersSearchQueryGender';
export * from './usersTemp';
export * from './usersTempDataItem';
export * from './usersTempDataItemAnimeStats';
export * from './usersTempDataItemFavorites';
export * from './usersTempDataItemImages';
export * from './usersTempDataItemImagesJpg';
export * from './usersTempDataItemImagesWebp';
export * from './usersTempDataItemMangaStats';
export * from './watchEpisodes';
export * from './watchEpisodesAllOf';
export * from './watchEpisodesAllOfDataItem';
export * from './watchEpisodesAllOfDataItemEpisodesItem';
export * from './watchPromos';
export * from './watchPromosAllOf';
export * from './watchPromosAllOfAllOf';
export * from './watchPromosAllOfAllOfTwo';
export * from './watchPromosAllOfAllOfTwoDataItem';