/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */

export interface ArtistSchema {
  /** Other names by which the artist is known. */
  aliases: string[];
  /** The artist's ID. */
  id: number;
  /** The character's ID in the v2 API. Format: UUID */
  id_v2?: string;
  /** An attempt to serve an artist PFP. This will probably stay outdated if they change their image after we upload it (they probably will at some point). */
  image_url: string;
  /** A list of links to official pages for the artist, like SNS or their website. They may be outdated if the artist changes their URL. */
  links: string[];
  /** The artist's name. */
  name: string;
  /** Does the artist allow you to use their art for AI projects (AI training)? */
  policy_ai?: boolean;
  /** Are you required to credit the artist when using their art? */
  policy_credit?: boolean;
  /** Does this artist allow you to repost their art in other places? */
  policy_repost: boolean;
}
