/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */

export interface CharacterSchema {
  /** All the ages the character officially has/has officially had. */
  ages: number[];
  /** Other names by which the character is known. */
  aliases: string[];
  /** The character's birthday. Format: MM/DD */
  birthday: string;
  /** A description of the character. */
  description: string;
  /** The character's gender. */
  gender: string;
  /** The the character's height (in cm). */
  height: number;
  /** The character's ID. */
  id: number;
  /** The character's ID in the v2 API. Format: UUID */
  id_v2: string;
  /** The character's name. */
  name: string;
  /** The character's nationality. */
  nationality: string;
  /** All the occupations the character officially has/has officially had. */
  occupations: string[];
  /** The character's species. */
  species: string;
  /** The character's weight (in kg). */
  weight: number;
}
