/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */
import type { ArtistSchema } from './artistSchema';
import type { CharacterSchema } from './characterSchema';
import type { TagSchema } from './tagSchema';

export interface ImageSchema {
  /** The artist of the image. */
  artist: ArtistSchema;
  /** The characters that appear in the image. */
  characters: CharacterSchema[];
  /** The dominant color of the image. [R, G, B] */
  color_dominant: number[];
  /** The color palette of the image. [[R, G, B], [R, G, B], ...] */
  color_palette: number[][];
  /** The time the image was created. This value is a POSIX timestamp. */
  created_at: number;
  /** The amount of frames that make up the image (if it's animated, check `is_animated`). */
  duration: number;
  /** The MD5 hash of the image. This is a(n almost) unique identifier for the image. */
  hash_md5: string;
  /** The perceptual hash of the image. This can be used to compare this image to other images. */
  hash_perceptual: string;
  /** The image's ID. */
  id: number;
  /** The image's ID in the v2 API. */
  id_v2: string;
  /** The height of the image. */
  image_height: number;
  /** The file size of the image. */
  image_size: number;
  /** The original/full image's URL. The format is always WEBP. */
  image_url: string;
  /** The width of the image. */
  image_width: number;
  /** Whether the image is animated or not. This'll become useful in the future when we add GIFs. */
  is_animated: boolean;
  /** Whether the image is flagged by mods. */
  is_flagged: boolean;
  /** Whether the image's idea is original or it uses characters/settings/content from another place (not original). */
  is_original: boolean;
  /** Whether the image is a screenshot of an anime ep./manga page. */
  is_screenshot: boolean;
  /** The age rating of the image. */
  rating: string;
  /** The height of the sample image. */
  sample_height: number;
  /** The file size of the sample image. */
  sample_size: number;
  /** The sample image's URL. It's a reduced version of the original image that is either 360px tall or 360px wide, whichever is smaller. The format is always WEBP. */
  sample_url: string;
  /** The width of the sample image. */
  sample_width: number;
  /** The source URL of the image (where it was first posted). */
  source: string;
  /** The source ID of the sauce in [NekoSauce](https://nekosauce.org). */
  source_id: number;
  /** The image's tags. */
  tags: TagSchema[];
  /** The time the image was last updated. This value is a POSIX timestamp. */
  updated_at: number;
  /** The verification level of the image. Normal users will only see images with this set to `verified`. */
  verification: string;
}
