/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */

export type NekosapiImagesApiImageReportParams = {
id?: number;
url?: string;
};
