/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */

export type NekosapiImagesApiRandomImageFileParams = {
/**
 * The age rating of the image.
 */
rating?: string[];
/**
 * Whether the image's idea is original or it uses characters/settings/content from another place (not original).
 */
is_original?: boolean;
/**
 * Whether the image is a screenshot of an anime ep./manga page.
 */
is_screenshot?: boolean;
/**
 * Whether the image is flagged by mods.
 */
is_flagged?: boolean;
/**
 * Whether the image is animated or not. This'll become useful in the future when we add GIFs.
 */
is_animated?: boolean;
/**
 * The artist's ID.
 */
artist?: number;
/**
 * The character's ID.
 */
character?: number[];
/**
 * The tag's ID.
 */
tag?: number[];
};
