/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */

export type NekosapiCharactersApiCharactersParams = {
search?: string;
/**
 * One or more of the character's (official) ages.
 */
age?: number[];
/**
 * The character's gender.
 */
gender?: string;
/**
 * The character's species.
 */
species?: string;
/**
 * The character's nationality.
 */
nationality?: string;
/**
 * Occupations the character officially has/has officially had.
 */
occupation?: string[];
limit?: number;
offset?: number;
};
