/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */

export type NekosapiArtistsApiArtistsParams = {
/**
 * Search term. Will return all tags with this term(s) in their name or description.
 */
search?: string;
/**
 * Does this artist allow you to repost their art in other places?
 */
policy_repost?: boolean;
/**
 * Are you required to credit the artist when using their art?
 */
policy_credit?: boolean;
/**
 * Does the artist allow you to use their art for AI projects (AI training)?
 */
policy_ai?: boolean;
limit?: number;
offset?: number;
};
