/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */

export type NekosapiImagesApiTagsParams = {
/**
 * Search for a tag by name or description.
 */
search?: string;
/**
 * Whether the tag is NSFW or not.
 */
is_nsfw?: boolean;
limit?: number;
offset?: number;
};
