/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Nekos API
 * An open source anime art API.
 * OpenAPI spec version: 3
 */

export interface TagSchema {
  /** A short description that says what the tag is and when it applies. */
  description: string;
  /** The tag's ID. */
  id: number;
  /** The tag's ID in the v2 API. Format: UUID */
  id_v2: string;
  /** Whether the tag is NSFW or not (usually, tags with this set to true will only be on NSFW images). */
  is_nsfw: boolean;
  /** The tag's name. */
  name: string;
  /** The subtype of the tag (format, character, setting). */
  sub: string;
}
