/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaUpdates API
 * This API powers our website.
Most API functions are public and do not require an account. For user-based functions, you must register an account.
Currently, user registration must be done through our main website and is disabled via this API.

Download OpenAPI Specification: [openapi.yaml](openapi.yaml)

Please contact us at the following emails if you have questions:

* lambchopsil@mangaupdates.com
* manick@mangaupdates.com

## Warranties

MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.

## Acceptable Use Policy

* You will credit MangaUpdates when using data provided by this API.
* You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data.
* You will NOT use MangaUpdates data or API in a way that will:
    * Deceive or defraud users
    * Assist or perform an illegal action
    * Create spam
    * Damage the database

We reserve the right to change this policy at any time.
 * OpenAPI spec version: 1.0.0
 */
import type { UserModelSearchV1 } from './userModelSearchV1';
import type { AuthorsModelV1Admin } from './authorsModelV1Admin';
import type { AuthorsModelV1AssociatedItem } from './authorsModelV1AssociatedItem';
import type { BirthdayModelV1 } from './birthdayModelV1';
import type { AuthorsModelV1Bloodtype } from './authorsModelV1Bloodtype';
import type { AuthorsModelV1Gender } from './authorsModelV1Gender';
import type { ImageModelV1 } from './imageModelV1';
import type { TimeV1 } from './timeV1';
import type { AuthorsModelV1Social } from './authorsModelV1Social';
import type { AuthorsModelV1Stats } from './authorsModelV1Stats';
import type { AuthorsModelV1Status } from './authorsModelV1Status';
import type { StatusDateModelV1 } from './statusDateModelV1';

export interface AuthorsModelV1 {
  actualname?: string;
  added_by?: UserModelSearchV1;
  admin?: AuthorsModelV1Admin;
  associated?: AuthorsModelV1AssociatedItem[];
  birthday?: BirthdayModelV1;
  birthplace?: string;
  bloodtype?: AuthorsModelV1Bloodtype;
  comments?: string;
  gender?: AuthorsModelV1Gender;
  genres?: string[];
  id?: number;
  image?: ImageModelV1;
  last_updated?: TimeV1;
  name?: string;
  social?: AuthorsModelV1Social;
  stats?: AuthorsModelV1Stats;
  status?: AuthorsModelV1Status;
  status_date?: StatusDateModelV1;
  url?: string;
}
