/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaUpdates API
 * This API powers our website.
Most API functions are public and do not require an account. For user-based functions, you must register an account.
Currently, user registration must be done through our main website and is disabled via this API.

Download OpenAPI Specification: [openapi.yaml](openapi.yaml)

Please contact us at the following emails if you have questions:

* lambchopsil@mangaupdates.com
* manick@mangaupdates.com

## Warranties

MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.

## Acceptable Use Policy

* You will credit MangaUpdates when using data provided by this API.
* You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data.
* You will NOT use MangaUpdates data or API in a way that will:
    * Deceive or defraud users
    * Assist or perform an illegal action
    * Create spam
    * Damage the database

We reserve the right to change this policy at any time.
 * OpenAPI spec version: 1.0.0
 */
import type { ForumForumModelV1Admin } from './forumForumModelV1Admin';
import type { ForumForumModelV1Category } from './forumForumModelV1Category';
import type { ForumTopicModelSearchV1 } from './forumTopicModelSearchV1';
import type { ForumAdminModelV1 } from './forumAdminModelV1';
import type { SeriesModelSearchV1 } from './seriesModelSearchV1';
import type { ForumForumModelV1Stats } from './forumForumModelV1Stats';

export interface ForumForumModelV1 {
  admin?: ForumForumModelV1Admin;
  category?: ForumForumModelV1Category;
  description?: string;
  forum_id?: number;
  last_topic?: ForumTopicModelSearchV1;
  moderators?: ForumAdminModelV1[];
  name?: string;
  position?: number;
  series?: SeriesModelSearchV1;
  stats?: ForumForumModelV1Stats;
  url?: string;
}
