/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaUpdates API
 * This API powers our website.
Most API functions are public and do not require an account. For user-based functions, you must register an account.
Currently, user registration must be done through our main website and is disabled via this API.

Download OpenAPI Specification: [openapi.yaml](openapi.yaml)

Please contact us at the following emails if you have questions:

* lambchopsil@mangaupdates.com
* manick@mangaupdates.com

## Warranties

MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.

## Acceptable Use Policy

* You will credit MangaUpdates when using data provided by this API.
* You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data.
* You will NOT use MangaUpdates data or API in a way that will:
    * Deceive or defraud users
    * Assist or perform an illegal action
    * Create spam
    * Damage the database

We reserve the right to change this policy at any time.
 * OpenAPI spec version: 1.0.0
 */
import type { SeriesModelUpdateV1Admin } from './seriesModelUpdateV1Admin';
import type { SeriesModelUpdateV1Anime } from './seriesModelUpdateV1Anime';
import type { SeriesModelUpdateV1AssociatedItem } from './seriesModelUpdateV1AssociatedItem';
import type { SeriesModelUpdateV1AuthorsItem } from './seriesModelUpdateV1AuthorsItem';
import type { CategoriesModelUpdateV1 } from './categoriesModelUpdateV1';
import type { SeriesModelUpdateV1GenresItem } from './seriesModelUpdateV1GenresItem';
import type { SeriesModelUpdateV1PublicationsItem } from './seriesModelUpdateV1PublicationsItem';
import type { SeriesModelUpdateV1PublishersItem } from './seriesModelUpdateV1PublishersItem';
import type { SeriesModelUpdateV1RelatedSeriesItem } from './seriesModelUpdateV1RelatedSeriesItem';
import type { SeriesModelUpdateV1Type } from './seriesModelUpdateV1Type';

export interface SeriesModelUpdateV1 {
  admin?: SeriesModelUpdateV1Admin;
  anime?: SeriesModelUpdateV1Anime;
  associated?: SeriesModelUpdateV1AssociatedItem[];
  authors?: SeriesModelUpdateV1AuthorsItem[];
  categories?: CategoriesModelUpdateV1[];
  completed?: boolean;
  description?: string;
  genres?: SeriesModelUpdateV1GenresItem[];
  licensed?: boolean;
  publications?: SeriesModelUpdateV1PublicationsItem[];
  publishers?: SeriesModelUpdateV1PublishersItem[];
  related_series?: SeriesModelUpdateV1RelatedSeriesItem[];
  status?: string;
  title?: string;
  type?: SeriesModelUpdateV1Type;
  year?: string;
}
