/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaUpdates API
 * This API powers our website.
Most API functions are public and do not require an account. For user-based functions, you must register an account.
Currently, user registration must be done through our main website and is disabled via this API.

Download OpenAPI Specification: [openapi.yaml](openapi.yaml)

Please contact us at the following emails if you have questions:

* lambchopsil@mangaupdates.com
* manick@mangaupdates.com

## Warranties

MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.

## Acceptable Use Policy

* You will credit MangaUpdates when using data provided by this API.
* You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data.
* You will NOT use MangaUpdates data or API in a way that will:
    * Deceive or defraud users
    * Assist or perform an illegal action
    * Create spam
    * Damage the database

We reserve the right to change this policy at any time.
 * OpenAPI spec version: 1.0.0
 */

export type UserSearchRequestV1Orderby = typeof UserSearchRequestV1Orderby[keyof typeof UserSearchRequestV1Orderby];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSearchRequestV1Orderby = {
  username: 'username',
  time_added: 'time_added',
  forum_posts: 'forum_posts',
  added_authors: 'added_authors',
  added_releases: 'added_releases',
  added_groups: 'added_groups',
  added_publishers: 'added_publishers',
  added_series: 'added_series',
} as const;
