/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaUpdates API
 * This API powers our website.
Most API functions are public and do not require an account. For user-based functions, you must register an account.
Currently, user registration must be done through our main website and is disabled via this API.

Download OpenAPI Specification: [openapi.yaml](openapi.yaml)

Please contact us at the following emails if you have questions:

* lambchopsil@mangaupdates.com
* manick@mangaupdates.com

## Warranties

MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.

## Acceptable Use Policy

* You will credit MangaUpdates when using data provided by this API.
* You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data.
* You will NOT use MangaUpdates data or API in a way that will:
    * Deceive or defraud users
    * Assist or perform an illegal action
    * Create spam
    * Damage the database

We reserve the right to change this policy at any time.
 * OpenAPI spec version: 1.0.0
 */
import type { UserModelV1Admin } from './userModelV1Admin';
import type { AvatarModelV1 } from './avatarModelV1';
import type { BirthdayModelV1 } from './birthdayModelV1';
import type { UserModelV1Gender } from './userModelV1Gender';
import type { TimeV1 } from './timeV1';
import type { UserModelV1Profile } from './userModelV1Profile';
import type { UserModelV1Stats } from './userModelV1Stats';

export interface UserModelV1 {
  admin?: UserModelV1Admin;
  age?: number;
  avatar?: AvatarModelV1;
  birthday?: BirthdayModelV1;
  email?: string;
  folding_at_home?: boolean;
  forum_title?: string;
  gender?: UserModelV1Gender;
  last_active_time?: TimeV1;
  location?: string;
  profile?: UserModelV1Profile;
  signature?: string;
  stats?: UserModelV1Stats;
  time_joined?: TimeV1;
  timezone?: number;
  url?: string;
  user_group?: string;
  user_group_name?: string;
  user_id?: number;
  username?: string;
}
