/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */
import type { LocalizedString } from './localizedString';

export interface AuthorCreate {
  biography?: LocalizedString;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?booth\.pm(/|$)
   */
  booth?: string | null;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?fanbox\.cc(/|$)
   */
  fanBox?: string | null;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?fantia\.jp(/|$)
   */
  fantia?: string | null;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?melonbooks\.co\.jp(/|$)
   */
  melonBook?: string | null;
  name: string;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?naver\.com(/|$)
   */
  naver?: string | null;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?nicovideo\.jp(/|$)
   */
  nicoVideo?: string | null;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?pixiv\.net(/|$)
   */
  pixiv?: string | null;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?skeb\.jp(/|$)
   */
  skeb?: string | null;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?tumblr\.com(/|$)
   */
  tumblr?: string | null;
  /**
   * @nullable
   * @pattern ^https?://twitter\.com(/|$)
   */
  twitter?: string | null;
  /**
   * @nullable
   * @pattern ^https?://
   */
  website?: string | null;
  /**
   * @nullable
   * @pattern ^https?://([\w-]+\.)?weibo\.(cn|com)(/|$)
   */
  weibo?: string | null;
  /**
   * @nullable
   * @pattern ^https?://www\.youtube\.com(/|$)
   */
  youtube?: string | null;
}
