/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */

export interface ChapterDraft {
  /**
   * @maxLength 8
   * @nullable
   * @pattern ^((0|[1-9]\d*)(\.\d+)?[a-z]?)?$
   */
  chapter: string | null;
  /**
   * @maxLength 512
   * @nullable
   * @pattern ^https?://
   */
  externalUrl?: string | null;
  /** @pattern ^\d{4}-[0-1]\d-([0-2]\d|3[0-1])T([0-1]\d|2[0-3]):[0-5]\d:[0-5]\d$ */
  publishAt?: string;
  /**
   * @maxLength 255
   * @nullable
   */
  title: string | null;
  /** @pattern ^[a-z]{2}(-[a-z]{2})?$ */
  translatedLanguage: string;
  /**
   * @maxLength 8
   * @nullable
   * @pattern ^((0|[1-9]\d*)(\.\d+)?[a-z]?)?$
   */
  volume: string | null;
}
