/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */
import type { GetChapterContentRatingItem } from './getChapterContentRatingItem';
import type { GetChapterIncludeFutureUpdates } from './getChapterIncludeFutureUpdates';
import type { GetChapterIncludeEmptyPages } from './getChapterIncludeEmptyPages';
import type { GetChapterIncludeFuturePublishAt } from './getChapterIncludeFuturePublishAt';
import type { GetChapterIncludeExternalUrl } from './getChapterIncludeExternalUrl';
import type { GetChapterOrderChapter } from './getChapterOrderChapter';
import type { GetChapterOrderCreatedAt } from './getChapterOrderCreatedAt';
import type { GetChapterOrderPublishAt } from './getChapterOrderPublishAt';
import type { GetChapterOrderReadableAt } from './getChapterOrderReadableAt';
import type { GetChapterOrderUpdatedAt } from './getChapterOrderUpdatedAt';
import type { GetChapterOrderVolume } from './getChapterOrderVolume';
import type { GetChapterIncludesItem } from './getChapterIncludesItem';

export type GetChapterParams = {
limit?: number;
offset?: number;
/**
 * Chapter ids (limited to 100 per request)
 */
'ids[]'?: string[];
title?: string;
'groups[]'?: string[];
uploader?: string | string[];
manga?: string;
'volume[]'?: string | string[];
chapter?: string | string[];
'translatedLanguage[]'?: string[];
'originalLanguage[]'?: string[];
'excludedOriginalLanguage[]'?: string[];
'contentRating[]'?: GetChapterContentRatingItem[];
'excludedGroups[]'?: string[];
'excludedUploaders[]'?: string[];
includeFutureUpdates?: GetChapterIncludeFutureUpdates;
includeEmptyPages?: GetChapterIncludeEmptyPages;
includeFuturePublishAt?: GetChapterIncludeFuturePublishAt;
includeExternalUrl?: GetChapterIncludeExternalUrl;
createdAtSince?: string;
updatedAtSince?: string;
publishAtSince?: string;
order?: {
  chapter?: GetChapterOrderChapter;
  createdAt?: GetChapterOrderCreatedAt;
  publishAt?: GetChapterOrderPublishAt;
  readableAt?: GetChapterOrderReadableAt;
  updatedAt?: GetChapterOrderUpdatedAt;
  volume?: GetChapterOrderVolume;
};
includes?: GetChapterIncludesItem[];
};
