/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */
import type { GetListIdFeedContentRatingItem } from './getListIdFeedContentRatingItem';
import type { GetListIdFeedIncludeFutureUpdates } from './getListIdFeedIncludeFutureUpdates';
import type { GetListIdFeedOrderChapter } from './getListIdFeedOrderChapter';
import type { GetListIdFeedOrderCreatedAt } from './getListIdFeedOrderCreatedAt';
import type { GetListIdFeedOrderPublishAt } from './getListIdFeedOrderPublishAt';
import type { GetListIdFeedOrderReadableAt } from './getListIdFeedOrderReadableAt';
import type { GetListIdFeedOrderUpdatedAt } from './getListIdFeedOrderUpdatedAt';
import type { GetListIdFeedOrderVolume } from './getListIdFeedOrderVolume';
import type { ReferenceExpansionChapter } from './referenceExpansionChapter';
import type { GetListIdFeedIncludeEmptyPages } from './getListIdFeedIncludeEmptyPages';
import type { GetListIdFeedIncludeFuturePublishAt } from './getListIdFeedIncludeFuturePublishAt';
import type { GetListIdFeedIncludeExternalUrl } from './getListIdFeedIncludeExternalUrl';

export type GetListIdFeedParams = {
limit?: number;
offset?: number;
'translatedLanguage[]'?: string[];
'originalLanguage[]'?: string[];
'excludedOriginalLanguage[]'?: string[];
'contentRating[]'?: GetListIdFeedContentRatingItem[];
'excludedGroups[]'?: string[];
'excludedUploaders[]'?: string[];
includeFutureUpdates?: GetListIdFeedIncludeFutureUpdates;
createdAtSince?: string;
updatedAtSince?: string;
publishAtSince?: string;
order?: {
  chapter?: GetListIdFeedOrderChapter;
  createdAt?: GetListIdFeedOrderCreatedAt;
  publishAt?: GetListIdFeedOrderPublishAt;
  readableAt?: GetListIdFeedOrderReadableAt;
  updatedAt?: GetListIdFeedOrderUpdatedAt;
  volume?: GetListIdFeedOrderVolume;
};
'includes[]'?: ReferenceExpansionChapter;
includeEmptyPages?: GetListIdFeedIncludeEmptyPages;
includeFuturePublishAt?: GetListIdFeedIncludeFuturePublishAt;
includeExternalUrl?: GetListIdFeedIncludeExternalUrl;
};
