/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */
import type { GetMangaIdFeedContentRatingItem } from './getMangaIdFeedContentRatingItem';
import type { GetMangaIdFeedIncludeFutureUpdates } from './getMangaIdFeedIncludeFutureUpdates';
import type { GetMangaIdFeedOrderChapter } from './getMangaIdFeedOrderChapter';
import type { GetMangaIdFeedOrderCreatedAt } from './getMangaIdFeedOrderCreatedAt';
import type { GetMangaIdFeedOrderPublishAt } from './getMangaIdFeedOrderPublishAt';
import type { GetMangaIdFeedOrderReadableAt } from './getMangaIdFeedOrderReadableAt';
import type { GetMangaIdFeedOrderUpdatedAt } from './getMangaIdFeedOrderUpdatedAt';
import type { GetMangaIdFeedOrderVolume } from './getMangaIdFeedOrderVolume';
import type { ReferenceExpansionChapter } from './referenceExpansionChapter';
import type { GetMangaIdFeedIncludeEmptyPages } from './getMangaIdFeedIncludeEmptyPages';
import type { GetMangaIdFeedIncludeFuturePublishAt } from './getMangaIdFeedIncludeFuturePublishAt';
import type { GetMangaIdFeedIncludeExternalUrl } from './getMangaIdFeedIncludeExternalUrl';

export type GetMangaIdFeedParams = {
limit?: number;
offset?: number;
'translatedLanguage[]'?: string[];
'originalLanguage[]'?: string[];
'excludedOriginalLanguage[]'?: string[];
'contentRating[]'?: GetMangaIdFeedContentRatingItem[];
'excludedGroups[]'?: string[];
'excludedUploaders[]'?: string[];
includeFutureUpdates?: GetMangaIdFeedIncludeFutureUpdates;
createdAtSince?: string;
updatedAtSince?: string;
publishAtSince?: string;
order?: {
  chapter?: GetMangaIdFeedOrderChapter;
  createdAt?: GetMangaIdFeedOrderCreatedAt;
  publishAt?: GetMangaIdFeedOrderPublishAt;
  readableAt?: GetMangaIdFeedOrderReadableAt;
  updatedAt?: GetMangaIdFeedOrderUpdatedAt;
  volume?: GetMangaIdFeedOrderVolume;
};
'includes[]'?: ReferenceExpansionChapter;
includeEmptyPages?: GetMangaIdFeedIncludeEmptyPages;
includeFuturePublishAt?: GetMangaIdFeedIncludeFuturePublishAt;
includeExternalUrl?: GetMangaIdFeedIncludeExternalUrl;
};
