/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */
import type { GetSearchMangaIncludedTagsMode } from './getSearchMangaIncludedTagsMode';
import type { GetSearchMangaExcludedTagsMode } from './getSearchMangaExcludedTagsMode';
import type { GetSearchMangaStatusItem } from './getSearchMangaStatusItem';
import type { GetSearchMangaPublicationDemographicItem } from './getSearchMangaPublicationDemographicItem';
import type { GetSearchMangaContentRatingItem } from './getSearchMangaContentRatingItem';
import type { GetSearchMangaOrderCreatedAt } from './getSearchMangaOrderCreatedAt';
import type { GetSearchMangaOrderFollowedCount } from './getSearchMangaOrderFollowedCount';
import type { GetSearchMangaOrderLatestUploadedChapter } from './getSearchMangaOrderLatestUploadedChapter';
import type { GetSearchMangaOrderRating } from './getSearchMangaOrderRating';
import type { GetSearchMangaOrderRelevance } from './getSearchMangaOrderRelevance';
import type { GetSearchMangaOrderTitle } from './getSearchMangaOrderTitle';
import type { GetSearchMangaOrderUpdatedAt } from './getSearchMangaOrderUpdatedAt';
import type { GetSearchMangaOrderYear } from './getSearchMangaOrderYear';
import type { ReferenceExpansionManga } from './referenceExpansionManga';
import type { GetSearchMangaHasAvailableChapters } from './getSearchMangaHasAvailableChapters';

export type GetSearchMangaParams = {
limit?: number;
offset?: number;
title?: string;
authorOrArtist?: string;
'authors[]'?: string[];
'artists[]'?: string[];
/**
 * Year of release or none
 */
year?: number | 'none';
'includedTags[]'?: string[];
includedTagsMode?: GetSearchMangaIncludedTagsMode;
'excludedTags[]'?: string[];
excludedTagsMode?: GetSearchMangaExcludedTagsMode;
'status[]'?: GetSearchMangaStatusItem[];
'originalLanguage[]'?: string[];
'excludedOriginalLanguage[]'?: string[];
'availableTranslatedLanguage[]'?: string[];
'publicationDemographic[]'?: GetSearchMangaPublicationDemographicItem[];
/**
 * Manga ids (limited to 100 per request)
 */
'ids[]'?: string[];
'contentRating[]'?: GetSearchMangaContentRatingItem[];
createdAtSince?: string;
updatedAtSince?: string;
order?: {
  createdAt?: GetSearchMangaOrderCreatedAt;
  followedCount?: GetSearchMangaOrderFollowedCount;
  latestUploadedChapter?: GetSearchMangaOrderLatestUploadedChapter;
  rating?: GetSearchMangaOrderRating;
  relevance?: GetSearchMangaOrderRelevance;
  title?: GetSearchMangaOrderTitle;
  updatedAt?: GetSearchMangaOrderUpdatedAt;
  year?: GetSearchMangaOrderYear;
};
'includes[]'?: ReferenceExpansionManga;
hasAvailableChapters?: GetSearchMangaHasAvailableChapters;
group?: string;
};
