/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */
import type { LocalizedString } from './localizedString';
import type { MangaAttributesContentRating } from './mangaAttributesContentRating';
import type { MangaAttributesLinks } from './mangaAttributesLinks';
import type { MangaAttributesPublicationDemographic } from './mangaAttributesPublicationDemographic';
import type { MangaAttributesState } from './mangaAttributesState';
import type { MangaAttributesStatus } from './mangaAttributesStatus';
import type { Tag } from './tag';

export interface MangaAttributes {
  altTitles?: LocalizedString[];
  availableTranslatedLanguages?: string[];
  chapterNumbersResetOnNewVolume?: boolean;
  contentRating?: MangaAttributesContentRating;
  createdAt?: string;
  description?: LocalizedString;
  isLocked?: boolean;
  /** @nullable */
  lastChapter?: string | null;
  /** @nullable */
  lastVolume?: string | null;
  latestUploadedChapter?: string;
  links?: MangaAttributesLinks;
  originalLanguage?: string;
  /** @nullable */
  publicationDemographic?: MangaAttributesPublicationDemographic;
  state?: MangaAttributesState;
  /** */
  status?: MangaAttributesStatus;
  tags?: Tag[];
  title?: LocalizedString;
  updatedAt?: string;
  /** @minimum 1 */
  version?: number;
  /**
   * Year of release
   * @nullable
   */
  year?: number | null;
}
