/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */

/**
 * Related Manga type, only present if you are on a Manga entity and a Manga relationship
 */
export type RelationshipRelated = typeof RelationshipRelated[keyof typeof RelationshipRelated];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RelationshipRelated = {
  monochrome: 'monochrome',
  main_story: 'main_story',
  adapted_from: 'adapted_from',
  based_on: 'based_on',
  prequel: 'prequel',
  side_story: 'side_story',
  doujinshi: 'doujinshi',
  same_franchise: 'same_franchise',
  shared_universe: 'shared_universe',
  sequel: 'sequel',
  spin_off: 'spin_off',
  alternate_story: 'alternate_story',
  alternate_version: 'alternate_version',
  preserialization: 'preserialization',
  colored: 'colored',
  serialization: 'serialization',
} as const;
