/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!

This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.

# Acceptable use policy

Usage of our services implies acceptance of the following:
- You **MUST** credit us
- You **MUST** credit scanlation groups if you offer the ability to read chapters
- You **CANNOT** run ads or paid services on your website and/or apps

These may change at any time for any and no reason and it is up to you check for updates from time to time.

# Security issues

If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.

 * OpenAPI spec version: 5.10.2
 */
import type { LocalizedString } from './localizedString';

export interface ScanlationGroupAttributes {
  altNames?: LocalizedString[];
  /** @nullable */
  contactEmail?: string | null;
  createdAt?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  discord?: string | null;
  exLicensed?: boolean;
  /** @nullable */
  focusedLanguage?: string[] | null;
  inactive?: boolean;
  /** @nullable */
  ircChannel?: string | null;
  /** @nullable */
  ircServer?: string | null;
  locked?: boolean;
  /**
   * @maxLength 128
   * @nullable
   * @pattern ^https:\/\/www\.mangaupdates\.com\/(group|publisher)(s\.html\?id=\d+|\/[\w-]+\/?([\w-]+)?(\/)?)$
   */
  mangaUpdates?: string | null;
  name?: string;
  official?: boolean;
  /**
   * Should respected ISO 8601 duration specification: https://en.wikipedia.org/wiki/ISO_8601#Durations
   * @pattern ^(P([1-9]|[1-9][0-9])D)?(P?([1-9])W)?(P?T(([1-9]|1[0-9]|2[0-4])H)?(([1-9]|[1-5][0-9]|60)M)?(([1-9]|[1-5][0-9]|60)S)?)?$
   */
  publishDelay?: string;
  /**
   * @nullable
   * @pattern ^https?://
   */
  twitter?: string | null;
  updatedAt?: string;
  verified?: boolean;
  /** @minimum 1 */
  version?: number;
  /** @nullable */
  website?: string | null;
}
