/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PanelsDesu API
 * The official API for PanelsDesu
 * OpenAPI spec version: 1.0.0
 */
import type { GetPanelGetPanel200Manga } from './getPanelGetPanel200Manga';
import type { GetPanelGetPanel200OtherPanelsItem } from './getPanelGetPanel200OtherPanelsItem';
import type { GetPanelGetPanel200Page } from './getPanelGetPanel200Page';
import type { GetPanelGetPanel200Panel } from './getPanelGetPanel200Panel';

export type GetPanelGetPanel200 = {
  manga?: GetPanelGetPanel200Manga;
  other_panels?: GetPanelGetPanel200OtherPanelsItem[];
  page?: GetPanelGetPanel200Page;
  panel?: GetPanelGetPanel200Panel;
};
