/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PanelsDesu API
 * The official API for PanelsDesu
 * OpenAPI spec version: 1.0.0
 */
import type { GetPanelGetSimilarPanels200MangaItem } from './getPanelGetSimilarPanels200MangaItem';
import type { GetPanelGetSimilarPanels200PagesItem } from './getPanelGetSimilarPanels200PagesItem';
import type { GetPanelGetSimilarPanels200PanelsItem } from './getPanelGetSimilarPanels200PanelsItem';

export type GetPanelGetSimilarPanels200 = {
  manga?: GetPanelGetSimilarPanels200MangaItem[];
  pages?: GetPanelGetSimilarPanels200PagesItem[];
  panels?: GetPanelGetSimilarPanels200PanelsItem[];
};
