/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PanelsDesu API
 * The official API for PanelsDesu
 * OpenAPI spec version: 1.0.0
 */

export type GetPanelGetPanel200Page = {
  chapter_number?: number;
  chapter_scrape_url?: string;
  created_at?: string;
  id?: string;
  image_url?: string;
  last_processed_at?: string;
  manga_id?: string;
  number?: number;
  scrape_url?: string;
};
