/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PanelsDesu API
 * The official API for PanelsDesu
 * OpenAPI spec version: 1.0.0
 */

export type GetPanelGetPanel200Manga = {
  all_titles?: string[];
  authors?: string[];
  chapter_count?: number;
  created_at?: string;
  icon_url?: string;
  id?: string;
  mal_id?: number;
  page_count?: number;
  panel_count?: number;
  /** @nullable */
  scrape_url?: string | null;
  tags?: string[];
  title?: string;
  /** @nullable */
  title_english?: string | null;
  /** @nullable */
  title_japanese?: string | null;
  updated_at?: string;
};
