/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PanelsDesu API
 * The official API for PanelsDesu
 * OpenAPI spec version: 1.0.0
 */
import type { GetSearchSearchMedia200MangaItem } from './getSearchSearchMedia200MangaItem';
import type { GetSearchSearchMedia200PagesItem } from './getSearchSearchMedia200PagesItem';
import type { GetSearchSearchMedia200PanelsItem } from './getSearchSearchMedia200PanelsItem';

export type GetSearchSearchMedia200 = {
  manga?: GetSearchSearchMedia200MangaItem[];
  pages?: GetSearchSearchMedia200PagesItem[];
  panels?: GetSearchSearchMedia200PanelsItem[];
};
