/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PanelsDesu API
 * The official API for PanelsDesu
 * OpenAPI spec version: 1.0.0
 */

export type GetStatsGetStats200 = {
  tags?: string[];
  total_manga?: number;
  total_pages?: number;
  total_panels?: number;
};
