/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PanelsDesu API
 * The official API for PanelsDesu
 * OpenAPI spec version: 1.0.0
 */

export type GetSearchSearchMediaParams = {
/**
 * Number of results to return
 */
limit?: string;
/**
 * Search query
 */
q: string;
};
