/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PanelsDesu API
 * The official API for PanelsDesu
 * OpenAPI spec version: 1.0.0
 */

export * from './getPanelGetPanel200';
export * from './getPanelGetPanel200Manga';
export * from './getPanelGetPanel200OtherPanelsItem';
export * from './getPanelGetPanel200Page';
export * from './getPanelGetPanel200Panel';
export * from './getPanelGetSimilarPanels200';
export * from './getPanelGetSimilarPanels200MangaItem';
export * from './getPanelGetSimilarPanels200PagesItem';
export * from './getPanelGetSimilarPanels200PanelsItem';
export * from './getPanelGetSimilarPanelsParams';
export * from './getSearchSearchMedia200';
export * from './getSearchSearchMedia200MangaItem';
export * from './getSearchSearchMedia200PagesItem';
export * from './getSearchSearchMedia200PanelsItem';
export * from './getSearchSearchMediaParams';
export * from './getStatsGetStats200';